#version 430

layout(local_size_x = 16, local_size_y=16) in;
layout(rgba32f, binding = 0) uniform image2D imgOutput;

uniform int u_Samples;
uniform int u_maxBounces;
uniform int u_CurrentSample;
uniform int u_SamplesPerPass;
uniform vec3 u_CamPos;
uniform vec3 u_CamFor;
uniform vec3 u_CamUp;
uniform vec3 u_CamRight;
uniform float u_Fov;

#define TYPE_SPHERE             0
#define TYPE_PLANE              1

#define MATERIAL_LAMBERTIAN     0
#define MATERIAL_METAL          1
#define MATERIAL_DIELECTRIC     2

struct Ray{
    vec3 o;
    vec3 d;
};

struct Object{
    int type;
    int material;
    float matParam1;
    float matParam2;
    vec3 colour;
    float matParam3;
    vec3 pos;
    float matParam4;
    vec3 normal;
    float matParam5;
    float radius;
    float height;
    float matParam6;
    float additionalParam;
};

struct RayHit{
    vec3 point;
    vec3 normal;
    float t;
    vec3 colour;
    bool valid;
    bool frontFace;
    Object o;
};


layout(std430, binding = 1) buffer SceneData{
    Object objects[];
};

uint pcgHash(inout uint state) {
    state = state * 747796405u + 2891336453u;
    uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
    return (word >> 22u) ^ word;
}

float randomFloat(inout uint state) {
    return float(pcgHash(state)) / 4294967295.0;
}

vec3 randomInUnitSphere(inout uint state) {
    float z = randomFloat(state) * 2.0 - 1.0;
    float a = randomFloat(state) * 6.28318530718;
    float r = sqrt(1.0 - z * z);
    return vec3(r * cos(a), r * sin(a), z);
}