RayHit hitSphere(Object s, Ray r, float tMin, float tMax){
    RayHit hit;
    vec3 oc = s.pos - r.o;
    float a = dot(r.d, r.d);
    float h = dot(r.d, oc);
    float c = dot(oc, oc) - (s.radius * s.radius);

    float discrim = h*h - a*c;
    if(discrim < 0){
        hit.valid = false;
        return hit;
    }
    float sqrtd = sqrt(discrim);
    float root = (h - sqrtd) / a;

    if(root < tMin || root > tMax){
        root = (h + sqrtd) / a;
        if (root < tMin || root > tMax){
            hit.valid = false;
            return hit;
        }
    }
    hit.t = root;
    hit.point = r.o + hit.t * r.d;
    vec3 outwardsNormal = (hit.point - s.pos) / s.radius;
    hit.frontFace = dot(r.d, outwardsNormal) < 0.0;
    hit.normal = hit.frontFace ? outwardsNormal : -outwardsNormal;
    hit.o = s;
    hit.colour = s.colour;
    hit.valid = true;
    return hit;
}

RayHit hitPlane(Object p, Ray r, float tMin, float tMax){
    RayHit hit;
    if(dot(p.normal, r.d) == 0){
        hit.valid = false;
        return hit;
    }
    float mul = (-p.additionalParam - dot(p.normal, r.o))/(dot(p.normal, r.d));
    if(tMin > mul || tMax < mul){
        hit.valid = false;
        return hit;
    }
    hit.t = mul;
    hit.point = r.o + hit.t * r.d;
    hit.frontFace = dot(r.d, p.normal) < 0.0;
    hit.normal = hit.frontFace ? p.normal : -p.normal;
    hit.o = p;
    hit.colour = p.colour;
    hit.valid = true;
    return hit;

}

RayHit hitCylinder(Object c, Ray r, float tMin, float tMax){
    RayHit hit;
    c.normal = normalize(c.normal);
    //Normal for cylinder is normal for its caps, so its axis
    vec3 aVec = r.d - (dot(r.d, c.normal) * c.normal);
    vec3 delP = r.o - c.pos;
    vec3 cVec = delP - (dot(delP, c.normal) * c.normal);

    float a = dot(aVec, aVec);
    float b = 2 * dot(aVec, cVec);
    float cc = dot(cVec, cVec) - (c.radius * c.radius);
    float discrim = (b * b) - (4 * a * cc);

    if(discrim < 0){
        hit.valid = false;
        return hit;
    }

    float closestT = 3.402823466e+38f;
    vec3 bestNorm;
    bool hitFound = false;

    //check main cylinder
    if(abs(a) > 1e-6f){
        float sqrtDiscrim = sqrt(discrim);
        float[] roots = { (-b - sqrtDiscrim) / (2 * a), (-b + sqrtDiscrim) / (2 * a) };

        for (int i = 0; i < 2; i++){
            if(roots[i] < closestT && roots[i] < tMax && roots[i] > tMin){
                vec3 point = r.o + roots[i] * r.d;
                float y = dot(point - c.pos, c.normal);
                if(y >= -c.height/2.0f && y <= c.height/2.0f){
                    closestT = roots[i];
                    vec3 projectedY = y * c.normal;
                    bestNorm = normalize(point - c.pos - projectedY);
                    hitFound = true;
                }
            }
        }
    }
    //Check the caps
    //additionalParam = 1 if caps, else 0
    if(c.additionalParam == 1){
        float dirToAxis = dot(r.d, c.normal);
        if(abs(dirToAxis) > 1e-6f){
            float[] capsY = {c.height/2.0f, -c.height/2.0f};
            vec3[] capNorms = {c.normal, -c.normal};

            for (int i = 0; i < 2; i++){
                float tCap = (capsY[i] - dot(delP, c.normal)) / dirToAxis;

                if(tCap < closestT && tCap < tMax && tCap > tMin){
                    vec3 pCap = r.o + tCap * r.d;
                    vec3 capPos = c.pos + (capsY[i] * c.normal);
                    vec3 distVec = pCap - capPos;
                    if(dot(distVec, distVec) <= (c.radius * c.radius)){
                        closestT = tCap;
                        bestNorm = capNorms[i];
                        hitFound = true;
                    }
                }
            }
        }
    }
    if(!hitFound){
        hit.valid = false;
        return hit;
    }
    vec3 hitPoint = r.o + closestT * r.d;
    hit.point = hitPoint;
    hit.t = closestT;
    hit.colour = c.colour;
    hit.valid = true;
    hit.frontFace = dot(r.d, bestNorm) < 0.0;
    hit.normal = hit.frontFace ? bestNorm : -bestNorm;
    hit.o = c;
    return hit;
}

RayHit hitFrustrum(Object f, Ray r, float tMin, float tMax){
    RayHit hit;
    f.normal = normalize(f.normal);
    vec3 delP = r.o - f.pos;
    float cosSqrdTheta = pow(cos(f.radius), 2.0);
    float a = pow(dot(r.d, f.normal), 2.0) - cosSqrdTheta * dot(r.d, r.d);
    float b = 2 * (dot(r.d, f.normal) * dot(delP, f.normal) - cosSqrdTheta * dot(r.d, delP));
    float c = pow(dot(delP, f.normal), 2.0) - cosSqrdTheta * dot(delP, delP);

    float discrim = (b * b) - (4 * a * c);
    if(discrim < 0){
        hit.valid = false;
        return hit;
    }

    float bestT = 3.402823466e+38f;
    vec3 bestNorm;
    bool hitFound = false;

    if(abs(a) > 1e-6f){
        float sqrtDiscrim = sqrt(discrim);
        float[] roots = { (-b - sqrtDiscrim) / (2 * a), (-b + sqrtDiscrim) / (2 * a) };

        for (int i = 0; i < 2; i++){
            if (roots[i] < bestT && roots[i] < tMax && roots[i] > tMin){
                vec3 intersect = r.o + roots[i] * r.d;
                vec3 intersectToPoint = intersect - f.pos;
                float h = dot(intersectToPoint, f.normal);
                if(h <= f.height && h >= f.shapeParam1){
                    bestT = roots[i];
                    hitFound = true;
                    bestNorm = normalize(intersectToPoint - ((h/cosSqrdTheta) * f.normal));
                }
            }
        }
    }

    if(f.additionalParam == 1){
        float dirToAxis = dot(r.d, f.normal);
        if(abs(dirToAxis) > 1e-6f){
            vec3[] capNorms = {-f.normal, f.normal};
            float[] capHeights = {f.shapeParam1, f.height};
            for (int i = 0; i < 2; i++){
                if(capHeights[i] == 0){
                    continue;
                }
                vec3 capBase = f.pos + capHeights[i] * f.normal;
                float multiplier = dot(capBase - r.o, f.normal) / dot(r.d, f.normal);
                if(multiplier < bestT && multiplier > tMin && multiplier < tMax){
                    vec3 intersect = r.o + multiplier * r.d;
                    if(pow(length(intersect - capBase), 2.0) <= pow(capHeights[i] * tan(f.radius), 2.0)){
                        bestT = multiplier;
                        hitFound = true;
                        bestNorm = capNorms[i];
                    }
                }
            }
        }
    }

    if(!hitFound){
        hit.valid = false;
        return hit;
    }

    vec3 hitPoint = r.o + bestT * r.d;
    hit.point = hitPoint;
    hit.t = bestT;
    hit.colour = f.colour;
    hit.valid = true;
    hit.frontFace = dot(r.d, bestNorm) < 0.0;
    hit.normal = hit.frontFace ? bestNorm : -bestNorm;
    hit.o = f;
    return hit;
}


RayHit hitDisk(Object d, Ray r, float tMin, float tMax){
    RayHit hit;
    if(dot(d.normal, r.d) == 0){
        hit.valid = false;
        return hit;
    }
    float mul = (-d.additionalParam - dot(d.normal, r.o))/(dot(d.normal, r.d));
    if(tMin > mul || tMax < mul){
        hit.valid = false;
        return hit;
    }
    vec3 point = r.o + mul * r.d;
    float dist = distance(point, d.pos);
    if(dist > d.radius){
        hit.valid = false;
        return hit;
    }
    hit.t = mul;
    hit.point = point;
    hit.frontFace = dot(r.d, d.normal) < 0.0;
    hit.normal = hit.frontFace ? d.normal : -d.normal;
    hit.o = d;
    hit.colour = d.colour;
    hit.valid = true;
    return hit;
}

RayHit rayIntersect(Ray r, float tMin, float tMax){
    RayHit closestHit;
    closestHit.valid = false;
    for (int i = 0; i < objects.length(); i++){
        RayHit next;
        switch (objects[i].type){
            case TYPE_SPHERE:
                next = hitSphere(objects[i], r, tMin, tMax);
                break;
            case TYPE_PLANE:
                next = hitPlane(objects[i], r, tMin, tMax);
                break;
            case TYPE_CYLINDER:
                next = hitCylinder(objects[i], r, tMin, tMax);
                break;
            case TYPE_FRUSTRUM:
                next = hitFrustrum(objects[i], r, tMin, tMax);
                break;
            case TYPE_DISK:
                next = hitDisk(objects[i], r, tMin, tMax);
                break;
        }
        if(!closestHit.valid){
            closestHit = next;
            if(next.valid){
                tMax = next.t;
            }
        }
        else if(!next.valid){

        }
        else if(closestHit.t > next.t){
            closestHit = next;
            tMax = closestHit.t;
        }
    }
    return closestHit;
}