float reflectance(float cosine, float refIdx){
    float r0 = (1.0 - refIdx) / (1.0 + refIdx);
    r0 = r0 * r0;
    return r0 + (1.0 - r0) * pow((1.0 - cosine), 5.0);
}

bool scatter(Ray r, RayHit hit, out vec3 colour, out Ray scattered, inout uint rngState){
    if(hit.o.material == MATERIAL_LAMBERTIAN){
        vec3 scatteredDirection = hit.normal + normalize(randomInUnitSphere(rngState));
        if(length(scatteredDirection) < 0.00001){
            scatteredDirection = hit.normal;
        }
        scattered = Ray(hit.point, normalize(scatteredDirection));
        colour = hit.colour;
        return true;
    }
    else if(hit.o.material == MATERIAL_METAL){
        vec3 reflected = normalize(reflect(r.d, hit.normal));
        scattered = Ray(hit.point, normalize(reflected + hit.o.matParam1 * randomInUnitSphere(rngState)));
        colour = hit.colour;
        return dot(scattered.d, hit.normal) > 0.0;
    }
    else if(hit.o.material == MATERIAL_DIELECTRIC){
        colour = hit.colour;
        float ri = hit.frontFace ? (1.0/hit.o.matParam1): hit.o.matParam1;
        vec3 unitD = normalize(r.d);

        float cosTheta = min(dot(-unitD, hit.normal), 1.0);
        float sinTheta = sqrt(1.0 - (cosTheta * cosTheta));

        bool cannotRefract = ri * sinTheta > 1.0;
        vec3 direction;

        if(cannotRefract || reflectance(cosTheta, ri) > randomFloat(rngState)){
            direction = reflect(unitD, hit.normal);
        }
        else{
            direction = refract(unitD, hit.normal, ri);
        }
        scattered = Ray(hit.point, direction);
        return true;
    }
    return false;
}